# Generated by Django 6.0.3 on 2026-03-19 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('words', models.JSONField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests', models.IntegerField(default=0)),
                ('best_wpm', models.FloatField(default=0)),
                ('average_wpm', models.FloatField(default=0)),
                ('best_accuracy', models.FloatField(default=0)),
                ('average_accuracy', models.FloatField(default=0)),
                ('total_typing_time', models.IntegerField(default=0, help_text='Total typing time in seconds')),
                ('total_correct_characters', models.IntegerField(default=0)),
                ('total_incorrect_characters', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypingTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.IntegerField(help_text='Duration of the test in seconds')),
                ('test_mode', models.CharField(choices=[('time', 'Time'), ('words', 'Words')], default='time', max_length=20)),
                ('words_typed', models.IntegerField(default=0)),
                ('correct_characters', models.IntegerField(default=0)),
                ('incorrect_characters', models.IntegerField(default=0)),
                ('total_characters_attempted', models.IntegerField(default=0)),
                ('wpm', models.FloatField(help_text='Words Per Minute')),
                ('raw_wpm', models.FloatField(help_text='Raw WPM before accuracy penalty')),
                ('accuracy', models.FloatField(help_text='Accuracy percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mistakes_count', models.IntegerField(default=0, help_text='Total mistakes made')),
                ('time_penalty_seconds', models.FloatField(default=0, help_text='Total time deducted due to mistakes')),
                ('adjusted_duration', models.FloatField(help_text='Duration after time penalties (in seconds)')),
                ('passed', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_results', to=settings.AUTH_USER_MODEL)),
                ('word_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='typemaster.wordlist')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='typemaster__created_bb08cb_idx'), models.Index(fields=['user', '-created_at'], name='typemaster__user_id_61ff26_idx'), models.Index(fields=['wpm'], name='typemaster__wpm_f22933_idx')],
            },
        ),
    ]
